# Application Configuration
app.url=https://www.agoda.com/
app.timeout=30
app.implicit.wait=10
app.page.load.timeout=30

# Browser Configuration
browser=chrome
headless=false
maximize=true

# Test Envitronment
env=qa

# Report Configuration
report.path=test-output/extent-reports
screenshot.path=test-output/screenshots